# (!) DO NOT CHANGE (!)
version: 2

# (!) NOTICE (!)
# You can use '&' for color codes.
# use {title} in RankSystems config.yml to replace it with player's title
# e.g: "{chat_ranks_prefix}{chat_name-color}{display_name}{title}{chat_format}{message}"
#
# Permissions will be automatically applied. e.g:
# playertitles.title.example

# Configurable information for the plugin.
settings:
  titles-per-page: 5 # How many titles to show per page
  message:
    - "&r&aSelected Title: '{title}&a'"
  no-title-perm: "&r&cYou don't have access to this title!"
  # Both the name and lore support the {title} placeholder.
  item:
    type: "paper"
    name: "&r&l&eTITLE '&r&f{title}&l&e'&r"
    lore: 
      - "&r&7Right Click (in your hand) to unlock"
      - "&r&7the &f{title} &7on this server."
    title-type: "display" # Either "display" or "identifier", this will show the titles identifier, or the display (Identifier will autocapitalize the first letter)
  claim-message: "&r&aYou have unlocked the '&f{title}&a' title!"
  claim-sound: "random.levelup"

titles:
  example: # Identifier 
    display: "&r&8[&cExample&8]&r"
  test:
    display: "&r&5Test&r"

# If the command exists, e.g "titles", the plugin will automatically unregister the vanilla command.
# IF renaming it to a vanilla command, make sure you wont need to use the command as it will no longer be available unless the
# command name is changed.
commands:
  titles:
    name: "title" # Main command
    description: "Open titles menu"
    aliases:
      - titles

# Configurable information for the forms available by the plugin.
forms:
  titles:
    name: "&r&8Titles"
    back: "&r&8Previous Page"
    next: "&r&8Next Page"
    
